exclude: conf.py
repos:
# Black | Formatting and Style
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
    -   id: black
        language_version: python3
# Pre-Commit Hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
# Pre-Commit
-   repo: https://github.com/pre-commit/pre-commit
    rev: v4.0.1
    hooks:
    -   id: validate_manifest
# Flake8
-   repo: https://github.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-typing-imports==1.5.0
# AutoPEP8 | Formats code to the PEP 8 style guide
-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
    -   id: autopep8
# PyUpgrade | Automatically upgrade syntax for newer Python versions.
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
    -   id: pyupgrade
        args: ["--py36-plus"]
# Isort | Sort module imports.
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
# Add Trailing Comma
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
        args: ["--py36-plus"]
# Commitizen | Ensuring conventional commits.
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.30.0
    hooks:
    -   id: commitizen
        stages: ["commit-msg"]
